spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/blog_engine
#    username: postgres
#    password: postgres
    url: jdbc:mysql://localhost:3306/blog_engine?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      enabled: true
      max-file-size: 6MB
  mail:
    host: smtp.yandex.ru
    port: 465
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      "mail.smtp.ssl.enable": true
      "mail.smtp.auth": true

blog:
  main-link: ${MAIN_LINK}
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: sgoshaa@yandex.ru
  copyright: Игорь Спирин
  copyrightFrom: 2021

cloudinary:
  cloud_name: ${CLOUD_NAME}
  api_key: ${API_KEY}
  api_secret: ${API_SECRET}
