spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/blog_engine
#    username: postgres
#    password: postgres
    url: jdbc:mysql://localhost:3306/blog_engine?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/dbchangelog-master.xml
    drop-first: true