CREATE TABLE captcha_codes
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time        TIMESTAMP WITHOUT TIME ZONE,
    code        VARCHAR(255),
    secret_code VARCHAR(255),
    CONSTRAINT pk_captcha_codes PRIMARY KEY (id)
);

CREATE TABLE global_settings
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code  VARCHAR(255),
    name  VARCHAR(255),
    value VARCHAR(255),
    CONSTRAINT pk_global_settings PRIMARY KEY (id)
);

CREATE TABLE post_comments
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_id INTEGER,
    post_id   INTEGER,
    user_id   INTEGER,
    time      TIMESTAMP WITHOUT TIME ZONE,
    text      VARCHAR(255),
    CONSTRAINT pk_post_comments PRIMARY KEY (id)
);

CREATE TABLE post_votes
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER,
    post_id INTEGER,
    time    TIMESTAMP WITHOUT TIME ZONE,
    value   SMALLINT,
    CONSTRAINT pk_post_votes PRIMARY KEY (id)
);

CREATE TABLE posts
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active         SMALLINT,
    moderation_status VARCHAR(255),
    moderator_id      INTEGER,
    user_id           INTEGER,
    time              TIMESTAMP WITHOUT TIME ZONE,
    text              VARCHAR(255),
    view_count        INTEGER,
    CONSTRAINT pk_posts PRIMARY KEY (id)
);

CREATE TABLE tag2post
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id INTEGER,
    tag_id  INTEGER,
    CONSTRAINT pk_tag2post PRIMARY KEY (id)
);

CREATE TABLE tags
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_tags PRIMARY KEY (id)
);

CREATE TABLE users
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_moderator SMALLINT,
    reg_time     TIMESTAMP WITHOUT TIME ZONE,
    name         VARCHAR(255),
    email        VARCHAR(255),
    password     VARCHAR(255),
    code         VARCHAR(255),
    photo        VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE posts
    ADD CONSTRAINT FK_POSTS_ON_MODERATOR FOREIGN KEY (moderator_id) REFERENCES users (id);

ALTER TABLE posts
    ADD CONSTRAINT FK_POSTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE post_comments
    ADD CONSTRAINT FK_POST_COMMENTS_ON_PARENT FOREIGN KEY (parent_id) REFERENCES post_comments (id);

ALTER TABLE post_comments
    ADD CONSTRAINT FK_POST_COMMENTS_ON_POST FOREIGN KEY (post_id) REFERENCES posts (id);

ALTER TABLE post_comments
    ADD CONSTRAINT FK_POST_COMMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE post_votes
    ADD CONSTRAINT FK_POST_VOTES_ON_POST FOREIGN KEY (post_id) REFERENCES posts (id);

ALTER TABLE post_votes
    ADD CONSTRAINT FK_POST_VOTES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);